import browser from './browser-api'

/**
 * Keys `importSettings()` is allowed to restore.
 *
 * A settings file is untrusted input — it can be edited or shared by anyone —
 * and `storage.local` also holds fetched state the extension trusts implicitly
 * (`localConfig`, `proxyServerURI`, `domains`, `proxyStatuses`, ...). Writing a
 * file's contents in wholesale would let it pin a chosen proxy server or forge
 * the blocklist, so only genuine user-owned settings are restored and
 * everything else is re-derived on the next sync.
 *
 * Keep this in sync when adding a user-facing setting: a key missing here is
 * silently dropped on import.
 * @type {string[]}
 */
const IMPORTABLE_SETTINGS = [
  // General
  'enableExtension',
  'showNotifications',
  'currentRegionCode',
  // Registry
  'useRegistry',
  'useCustomRegistry',
  'customRegistryUrl',
  // User-curated domain lists
  'customProxiedDomains',
  'ignoredHosts',
  // Proxying
  'useProxy',
  'proxyAllTraffic',
  'useOwnProxy',
  'useLocalProxy',
  'activeProxyConfigName',
  'proxyTestTarget',
  'autoDeleteDeadProxies',
  // The user's proxy list and the chain that orders it. Dropping these would
  // make "export settings" useless as a backup of the thing users care about
  // most, so they are restored together with the legacy first-hop mirror.
  'customProxies',
  'proxyChain',
  'activeCustomProxyId',
  'customProxyProtocol',
  'customProxyServerURI',
  // Proxy subscriptions
  'proxySources',
  'proxySourcesEnabled',
  'proxySourcesIntervalMinutes',
  'proxySourcesUseProxy',
  'proxySourcesAutoTest',
  // Country pre-filter
  'proxyCountryFilterMode',
  'proxyCountryFilterList',
  'proxyCountryFilterAuto',
  'proxyCountryFilterRemoveUnknown',
]

/**
 * Proxy ids are generated by `ProxyManager.generateProxyId()` (a UUID, or
 * `p-<timestamp>-<random>`) and are interpolated into DOM attributes and CSS
 * attribute selectors by the options page. Restoring an id from a file means
 * accepting it from untrusted input, so it has to look like an id we issued.
 */
const SAFE_PROXY_ID = /^[A-Za-z0-9_-]{1,64}$/

/**
 * Rebuilds the proxy list from an imported file, keeping only entries that
 * have the shape the rest of the extension assumes. Anything malformed is
 * dropped rather than repaired: a half-valid proxy is not worth routing
 * traffic through.
 * @param value {*} Raw `customProxies` from the file.
 * @returns {Array<Object>} Clean proxy entries.
 */
const sanitizeCustomProxies = (value) => {
  if (!Array.isArray(value)) {
    return []
  }

  const seen = new Set()
  const proxies = []

  for (const item of value) {
    if (!item || typeof item !== 'object') {
      continue
    }

    const { id, name, protocol, uri, credentials, restricted } = item

    if (typeof id !== 'string' || !SAFE_PROXY_ID.test(id) || seen.has(id)) {
      continue
    }
    if (typeof protocol !== 'string' || !protocol) {
      continue
    }
    if (typeof uri !== 'string' || !uri.trim()) {
      continue
    }

    seen.add(id)
    proxies.push({
      id,
      name: typeof name === 'string' && name ? name : uri,
      protocol,
      uri,
      credentials: typeof credentials === 'string' ? credentials : '',
      restricted: !!restricted,
    })
  }

  return proxies
}

/**
 * Keeps only chain entries that point at a proxy that survived import (plus
 * the synthetic 'builtin' hop), preserving order and dropping duplicates.
 * @param value {*} Raw `proxyChain` from the file.
 * @param proxies {Array<Object>} Already-sanitized proxy list.
 * @returns {Array<string>} Clean chain.
 */
const sanitizeProxyChain = (value, proxies) => {
  if (!Array.isArray(value)) {
    return []
  }

  const known = new Set(proxies.map((proxy) => proxy.id))
  const chain = []

  for (const id of value) {
    if (typeof id !== 'string' || chain.includes(id)) {
      continue
    }
    if (id === 'builtin' || known.has(id)) {
      chain.push(id)
    }
  }

  return chain
}

class Settings {
  getName () {
    return 'Censor Tracker'
  }

  getDangerIcon () {
    return browser.runtime.getURL('images/icons/128x128/danger.png')
  }

  changePageIcon (tabId, filename) {
    const title = this.getName()
    const path = browser.runtime.getURL(`images/icons/128x128/${filename}.png`)

    if (browser.isFirefox) {
      browser.browserAction.setIcon({ tabId, path })
      browser.browserAction.setTitle({ title, tabId })
    } else {
      browser.action.setIcon({ tabId, path })
      browser.action.setTitle({ title, tabId })
    }
  }

  async showInstalledPage (tabId) {
    await browser.tabs.create({ url: 'installed.html' })
  }

  setDisableIcon (tabId) {
    this.changePageIcon(tabId, 'disabled')
  }

  setDefaultIcon (tabId) {
    this.changePageIcon(tabId, 'default')
  }

  setDangerIcon (tabId) {
    this.changePageIcon(tabId, 'danger')
  }

  setBlockedIcon (tabId) {
    this.changePageIcon(tabId, 'blocked')
  }

  async extensionEnabled () {
    const { enableExtension } =
      await browser.storage.local.get({ enableExtension: false })

    return enableExtension
  }

  async enableExtension () {
    await browser.storage.local.set({ enableExtension: true })
    console.log('Settings.enableExtension()')
  }

  async disableExtension () {
    await browser.storage.local.set({
      useProxy: false,
      enableExtension: false,
      showNotifications: false,
    })

    if (browser.isFirefox) {
      await browser.browserAction.setBadgeText({ text: '' })
    }

    console.log('Settings.disableExtension()')
  }

  async enableNotifications () {
    await browser.storage.local.set({ showNotifications: true })
  }

  async disableNotifications () {
    await browser.storage.local.set({ showNotifications: false })
  }

  async exportSettings () {
    const settings = await browser.storage.local.get(null)

    settings.domains = []
    settings.disseminators = []
    return settings
  }

  async importSettings (settings) {
    if (!settings || typeof settings !== 'object' || Array.isArray(settings)) {
      throw new Error('Invalid settings file: expected a JSON object.')
    }

    const restored = {}

    for (const key of IMPORTABLE_SETTINGS) {
      if (Object.prototype.hasOwnProperty.call(settings, key)) {
        restored[key] = settings[key]
      }
    }

    // The proxy list and chain are the only imported values the UI feeds back
    // into DOM attributes and selectors, so they get a shape check on top of
    // the key allow-list.
    if ('customProxies' in restored || 'proxyChain' in restored) {
      const proxies = sanitizeCustomProxies(restored.customProxies)

      restored.customProxies = proxies
      restored.proxyChain = sanitizeProxyChain(restored.proxyChain, proxies)
    }

    // A first hop that no longer exists would leave the legacy mirror keys
    // pointing at a proxy the list does not contain.
    if (typeof restored.activeCustomProxyId === 'string') {
      const chain = restored.proxyChain || []

      if (!chain.includes(restored.activeCustomProxyId)) {
        delete restored.activeCustomProxyId
      }
    }

    await browser.storage.local.clear()
    await browser.storage.local.set(restored)
  }
}

export default new Settings()
