name: Build

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g node-pre-gyp
    - run: npm install
    - run: npm run lint
    - run: npm run locales:check
      env:
        CI: true
        PROJECT_NAME: censortracker
