name: Build

on: [push, pull_request]

jobs:
  build:
    name: Lint & build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm run lint
      - run: npm run locales:check
        env:
          CI: true
          PROJECT_NAME: censortracker
      - name: Build (Chrome)
        run: npm run build:chrome:prod
      - name: Build (Firefox)
        run: npm run build:firefox:prod
